"""
Using the pre-formatted dictionary data below, create a dictionary and ask the user to enter a country.
If the country is in the dictionary, look up the associated capital city and display it.
If the country is not in the dictionary, display the message:

Sorry, <EnteredCountry> is not in the table.

Example
Please enter the country: united kingdom
The capital of United Kingdom is London.

Example
Please enter the country: manchester
Sorry, Manchester is not in the table.

"""
# Written on: April 18 2018
# Developed by: Michael Devenport
# Email: croxleyway@gmail.com

# Lab8-2 Q2 ( Fetch value of 'dict' key if exists else return failure statement )

country_prompt = "Please enter the country: "
return_success = "The capital of {} is {}."
return_failure = "Sorry, {} is not in the table."

# Set 'dict',
# first word equal to key type. second word references value.
country_to_capital = {
    'Afghanistan': 'Kabul',
    'Albania': 'Tirana',
    'Andorra': 'Andorra la Vella',
    'Angola': 'Luanda',
    'Antigua and Barbuda': 'St. John’s',
    'Argentina': 'Buenos Aires',
    'Armenia': 'Yerevan',
    'Australia': 'Canberra',
    'Austria': 'Vienna',
    'Azerbaijan': 'Baku',
    'Bahamas': 'Nassau',
    'Bahrain': 'Manama',
    'Bangladesh': 'Dhaka',
    'Barbados': 'Bridgetown',
    'Belarus': 'Minsk',
    'Belgium': 'Brussels',
    'Belize': 'Belmopan',
    'Benin': 'Cotonou',
    'Bhutan': 'Thimphu',
    'Bolivia': 'La Paz and Sucre',
    'Bosnia and Herzegovina': 'Sarajevo',
    'Botswana': 'Gaborone',
    'Brazil': 'Brasília',
    'Brunei': 'Bandar Seri Begawan',
    'Bulgaria': 'Sofia',
    'Burkina Faso': 'Ouagadougou',
    'Burundi': 'Bujumbura',
    'Cambodia': 'Phnom Penh',
    'Cameroon': 'Yaoundé',
    'Canada': 'Ottawa',
    'Cape Verde': 'Praia',
    'Cayman Islands': 'George Town',
    'Central African Republic': 'Bangui',
    'Chad': 'N’Djamena',
    'Chile': 'Santiago',
    'China': 'Beijing',
    'Colombia': 'Bogotá',
    'Comoros': 'Moroni',
    'Costa Rica': 'San José',
    'Côte d’Ivoire': 'Yamoussoukro',
    'Croatia': 'Zagreb',
    'Cuba': 'Havana',
    'Cyprus': 'Nicosia',
    'Czech Republic': 'Prague',
    'Democratic Republic of the Congo': 'Kinshasa',
    'Denmark': 'Copenhagen',
    'Djibouti': 'Djibouti',
    'Dominica': 'Roseau',
    'Dominican Republic': 'Santo Domingo',
    'East Timor': 'Dili',
    'Ecuador': 'Quito',
    'Egypt': 'Cairo',
    'El Salvador': 'San Salvador',
    'Equatorial Guinea': 'Malabo',
    'Eritrea': 'Asmara',
    'Estonia': 'Tallinn',
    'Ethiopia': 'Addis Ababa',
    'Fiji': 'Suva',
    'Finland': 'Helsinki',
    'France': 'Paris',
    'French Guiana': 'Cayenne',
    'Gabon': 'Libreville',
    'Georgia': 'Tbilisi',
    'Germany': 'Berlin',
    'Ghana': 'Accra',
    'Greece': 'Athens',
    'Grenada': 'St George’s',
    'Guatemala': 'Guatemala',
    'Guinea': 'Conakry',
    'Guinea-Bissau': '',
    'Guyana': 'Georgetown',
    'Haiti': 'Port-au-Prince',
    'Honduras': 'Tegucigalpa',
    'Hungary': 'Budapest',
    'Iceland': 'Reykjavik',
    'India': 'New Delhi',
    'Indonesia': 'Jakarta',
    'Iran': 'Tehran',
    'Iraq': 'Baghdad',
    'Israel': 'Jerusalem',
    'Italy': 'Rome',
    'Jamaica': 'Kingston',
    'Japan': 'Tokyo',
    'Jordan': 'Amman',
    'Kazakhstan': 'Astana',
    'Kenya': 'Nairobi',
    'Kiribati': 'South Tarawa',
    'Kuwait': 'Kuwait',
    'Kyrgyzstan': 'Bishkek',
    'Laos': 'Vientiane',
    'Latvia': 'Riga',
    'Lebanon': 'Beirut',
    'Lesotho': 'Maseru',
    'Liberia': 'Monrovia',
    'Libya': 'Tripoli',
    'Liechtenstein': 'Vaduz',
    'Lithuania': 'Vilnius',
    'Luxembourg': 'Luxembourg City',
    'Madagascar': 'Antananarivo',
    'Malawi': 'Lilongwe',
    'Malaysia': 'Kuala Lumpur',
    'Maldives': 'Malé',
    'Mali': 'Bamako',
    'Malta': 'Valletta',
    'Marshall Islands': 'Majuro',
    'Mauritania': 'Nouakchott',
    'Mauritius': 'Port Louis',
    'Mexico': 'Mexico City',
    'Micronesia': 'Palikir',
    'Moldova': 'Chisinau',
    'Monaco': 'Monaco',
    'Mongolia': 'Ulaanbaatar',
    'Montenegro': 'Podgorica',
    'Morocco': 'Rabat',
    'Mozambique': 'Maputo',
    'Myanmar': 'Naypyidaw',
    'Namibia': 'Windhoek',
    'Nauru': 'Yaren',
    'Nepal': 'Kathmandu',
    'Netherlands ': 'Amsterdam',
    'New Zealand': 'Wellington',
    'Nicaragua': 'Managua',
    'Niger': 'Niamey',
    'Nigeria': 'Abuja',
    'North Korea': 'Pyongyang',
    'Norway': 'Oslo',
    'Oman': 'Muscat',
    'Pakistan': 'Islamabad',
    'Palau': 'Koror',
    'Palestine': 'Jerusalem',
    'Panama': 'Panama City',
    'Papua New Guinea': 'Port Moresby',
    'Paraguay': 'Asuncion',
    'Peru': 'Lima',
    'Philippines': 'Manila',
    'Poland': 'Warsaw',
    'Portugal': 'Lisbon',
    'Puerto Rico': 'San Juan',
    'Qatar': 'Doha',
    'Republic of Ireland': 'Dublin',
    'Republic of Macedonia': 'Skopje',
    'Republic of the Congo': 'Brazzaville',
    'Romania': 'Bucharest',
    'Russia': 'Moscow',
    'Rwanda': 'Kigali',
    'Saint Kitts and Nevis': 'Basseterre',
    'Saint Lucia': 'Castries',
    'Saint Vincent and the Grenadines': 'Kingstown',
    'Samoa': 'Apia',
    'San Marino': 'San Marino',
    'São Tomé and Príncipe': 'São Tomé',
    'Saudi Arabia': 'Riyadh',
    'Senegal': 'Dakar',
    'Serbia': 'Belgrade',
    'Seychelles': 'Victoria',
    'Sierra Leone': 'Freetown',
    'Singapore': 'Singapore',
    'Slovakia': 'Bratislava',
    'Slovenia': 'Ljubljana',
    'Solomon Islands': 'Honiara',
    'Somalia': 'Mogadishu',
    'South Africa': 'Pretoria',
    'South Korea': 'Seoul',
    'South Sudan': 'Juba',
    'Spain': 'Madrid',
    'Sri Lanka': 'Colombo',
    'Sudan': 'Khartoum',
    'Suriname': 'Paramaribo',
    'Swaziland': 'Mbabane',
    'Sweden': 'Stockholm',
    'Switzerland': 'Bern',
    'Syria': 'Damascus',
    'Taiwan': 'Taipei',
    'Tajikistan': 'Dushanbe',
    'Tanzania': 'Dodoma',
    'Thailand': 'Bangkok',
    'The Gambia': 'Banjul',
    'Togo': 'Lome',
    'Tonga': 'Nuku’alofa',
    'Trinidad and Tobago': 'Port of Spain',
    'Tunisia': 'Tunis',
    'Turkey': 'Ankara',
    'Turkmenistan': 'Asgabat',
    'Turks and Caicos': 'Cockburn Town',
    'Tuvalu': 'Funafuti',
    'Uganda': 'Kampala',
    'Ukraine': 'Kyiv or Kiev',
    'United Arab Emirates': 'Abu Dhabi',
    'United Kingdom': 'London',
    'United States': 'Washington DC',
    'Uruguay': 'Montevideo',
    'Uzbekistan': 'Tashkent',
    'Vanuatu': 'Port Vila',
    'Vatican City': 'Vatican City',
    'Venezuela': 'Caracas',
    'Vietnam': 'Hanoi',
    'Western Sahara': 'La’youn',
    'Yemen': 'Sana’a',
    'Zambia': 'Lusaka',
    'Zimbabwe': 'Harare'
}

country_key = input(country_prompt).strip().title()

# Rubies 'Ternary conditional' equivalent,
# if condition( second line ) evaluates to True success statement is returned from( first line ),
# else failure statement is returned.
# It's 3 lines of code instead of 4  & reads grammatically correct:
# "print return_success string formatted with the country_key & dict key value if condition True otherwise,
#  print return_failure string formatted with the requested key( which does not exist ;)"
# Neat! I know the Pythonistas( Davey ) will love this!

print(return_success.format(country_key, country_to_capital[country_key]))\
    if country_key in country_to_capital\
    else print(return_failure.format(country_key))
