"""
Write a program to display the following menu below.

There is a blank line just before "Please select ...".



Please select the number from one of the following options.
1) Enter a new item.
2) Remove an item by its element number.
3) Display the number of items in the list.
4) Display a list of the items.
5) Remove all items from the list.
9) Exit.



Just for Moodle, a blank line needs to be generated by using
print(" ")

"""

# Auth: Michael Devenport
# Email: croxleyway

# The line of text you need to use to generate the output is given below for you.
# Do not alter anything inside the quotes.

blank_line = " "
selection_prompt = "Please select the number from one of the following options."
new_item_prompt = "1) Enter a new item."
remove_one_item_prompt = "2) Remove an item by its element number."
count_items_prompt = "3) Display the number of items in the list."
display_items_prompt = "4) Display a list of the items."
remove_all_items_prompt = "5) Remove all items from the list."
exit_prompt = "9) Exit."

# Create a list of menu options

menu_options = [new_item_prompt, remove_one_item_prompt, count_items_prompt,
                display_items_prompt, remove_all_items_prompt, exit_prompt]
print(" ")
print(selection_prompt)

# Iterate our aggregate( menu_options )

for constituent in menu_options:
    print(constituent)